[system]
compatible=myfw-x86_64
bootloader=grub
bundle-formats=verity

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/sda2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/sda3
type=ext4
bootname=B

[slot.data.0]
device=/dev/sda4
type=ext4
