[system]
compatible=myfw-x86_64
bootloader=grub
grubenv=/efi/EFI/BOOT/grubenv
bundle-formats=verity

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs.A
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs.B
type=ext4
bootname=B

[slot.data.0]
device=/dev/disk/by-partlabel/data
type=ext4
